### ISSUE TITLE
Spanish accents disappear from figures but show up properly on paragraphs

### ISSUE THREAD

**Issue by sebastianvelez** [daqana/tikzDevice#164]
---
    title: 'Some title'
    author: 'This be me'
    date: '`r format(Sys.Date(), "%B %Y")`'
    lang: es
    header-includes: 
      - \usepackage{tikz}
    output: 
      pdf_document:
        fig_caption: yes
    ---

    ```{r global options, echo = F, message=F}
    library(knitr)
    opts_chunk$set(fig.width=6, fig.height=3.5, dev = 'tikz')
    ```

    I have some paragraphs that include cool accents like áspid. 

    If I run the next chunk in the R console I see the accent on the figure it generated. But the accent is 
    missing in the pdf. 

    ```{r}
    plot(pressure, main= "áspid")
    ```

**Comment by krlmlr** [comment]
Thanks. Can you please install the development version and show the output of `tikzDevice::tikzTest()` ?

**Comment by cenuno** [comment]
@krlmlr, is the version you're talking about the `master` branch of this particular repository?

After running
```R
devtools::install_github( repo = "daqana/tikzDevice" )
```

I receive the following error message after knitting the sample `.rmd` file that @sebastianvelez shared up above:

```
## Warning in (function (texString, cex = 1, face = 1, engine =
## getOption("tikzDefaultEngine"), : Attempting to calculate the width
## of a Unicode stringusing the pdftex engine. This may fail! See the
## Unicodesection of ?tikzDevice for more information.
```

**Comment by bellackn** [comment]
Hi @sebastianvelez, using `options( tikzDefaultEngine = "xetex" )` should indeed solve this, thanks @cenuno!

Closing this issue since it appears to be resolved. Please feel free, if this is still an issue, to leave a comment requesting this issue be reopened.
