### ISSUE TITLE
(another) TeX was unable to calculate metrics for the following string or character: m

### ISSUE THREAD

**Issue by ghost** [daqana/tikzDevice#171]
I'm trying to use knitr with lualatex using (as far as I can tell) texlive 2016 (I'm working on updating it) on nixos with lyx 2.2.3 and I can't get the basic example working. I've attached my lyx file.

[hu.zip](https://github.com/yihui/tikzDevice/files/1685172/hu.zip)

I've gone through the other related issues here but haven't managed to fix the problem.

I tried tikzTest("m") but I don't know how to get any useful information from it. Also I can't really tell how I'm supposed to be able to get to the output if Rscript removes any temporary files when it closes. I also can't really get the file paths either since they get truncated by the edge of the page in the pdf and I don't know how to deal with that either yet....

Thanks in advance... *sigh*

**Comment by 22459** [comment]
Here's my lyx log and the resulting pdf:
```11:44:34.023: Previewing ...
11:44:34.031: Rscript --verbose --no-save --no-restore "/nix/store/n5jrsxhvk6wa2i1w9s8av4qvla66y17n-lyx-2.2.3/share/lyx/scripts/lyxknitr.R" "/run/user/1000/lyx_tmpdir.oVQgVarO9108/lyx_tmpbuf1/""hu.Rnw" "/run/user/1000/lyx_tmpdir.oVQgVarO9108/lyx_tmpbuf1/""hu.tex" UTF-8 "/mnt/data/egyetem2/6felev/labs/env/templates/lyx/"
11:44:34.035: running
11:44:34.036:   '/nix/store/gabn1nxvi6izdpic65basr2df66ib65l-R-3.4.1/lib/R/bin/R --slave --no-restore --no-save --no-restore --file=/nix/store/n5jrsxhvk6wa2i1w9s8av4qvla66y17n-lyx-2.2.3/share/lyx/scripts/lyxknitr.
11:44:34.038: R --args /run/user/1000/lyx_tmpdir.oVQgVarO9108/lyx_tmpbuf1/hu.Rnw /run/user/1000/lyx_tmpdir.oVQgVarO9108/lyx_tmpbuf1/hu.tex UTF-8 /mnt/data/egyetem2/6felev/labs/env/templates/lyx/'
11:44:34.039: 
11:44:34.349: 
11:44:34.350: 
11:44:34.352: processing file: /run/user/1000/lyx_tmpdir.oVQgVarO9108/lyx_tmpbuf1/hu.Rnw
11:44:34.447: 
  |                                                                       
  |                                                                 |   0%
  |                                             
11:44:34.448:                           
  |......................                                           |  33%
11:44:34.450:   ordinary text without R code
11:44:34.451: 
11:44:34.452: 
  |                                                                       
  |...........................................                      |  67%
11:44:34.453: label: cars-demo (with options) 
11:44:34.454: List of 4
11:44:34.455:  $ dev       : chr "tikz"
11:44:34.455:  $ fig.width : num 4
11:44:34.456:  $ fig.height: num 2.8
11:44:34.457:  $ out.width : chr ".45\\textwidth"
11:44:34.458: 
11:44:38.790: 
  |                                                                       
  |.................................................................| 100%
11:44:38.794:   ordinary text without R code
11:44:38.797: 
11:44:38.808: 
11:44:38.812: output file: /run/user/1000/lyx_tmpdir.oVQgVarO9108/lyx_tmpbuf1/hu.tex
11:44:38.815: 
11:44:38.819: [1] "/run/user/1000/lyx_tmpdir.oVQgVarO9108/lyx_tmpbuf1/hu.tex"
11:44:38.829: lualatex "hu.tex"
11:44:38.992: This is LuaTeX, Version 0.95.0 (Web2C 2016/NixOS.org) 
11:44:38.996:  restricted system commands enabled.
11:44:38.999: (./hu.tex
11:44:39.002: LaTeX2e <2016/03/31> patch level 1
11:44:39.005: Babel <3.9r> and hyphenation patterns for 1 language(s) loaded.
11:44:39.010: 
11:44:39.470: 
11:44:39.479: luaotfload | main : initialization completed in 0.109 seconds
11:44:41.104: Successful preview of format: PDF (LuaTeX)```
[pdf.zip](https://github.com/yihui/tikzDevice/files/1685185/pdf.zip)

**Comment by 22459** [comment]
Would there be any way to improve the error reporting so that it's sufficient to look at the lyx log and not need to dig around deeply in files to get to the error messages?

**Comment by krlmlr** [comment]
Can you please try `tikzTest()` in the development version?

**Comment by 22459** [comment]
Here you go:
[files.zip](https://github.com/yihui/tikzDevice/files/1687430/files.zip)

**Comment by krlmlr** [comment]
Thanks. Could you please post the output of `tikzTest()`? I'm not sure how the `.zip` file is helpful.

**Comment by 22459** [comment]
Well, that was exactly my question. I don't know how to get the output. The best I was able to get was what's in the PDF.

The temporary files get removed after the Rscript finishes running.

**Comment by krlmlr** [comment]
What's the console output?

**Comment by 22459** [comment]
It's the same as in my first post, sorry. :/

**Comment by krlmlr** [comment]
Can I please see the console output of `tikzTest()`?

**Comment by 22459** [comment]
Do you mean in R?

**Comment by krlmlr** [comment]
If you run `tikzTest()` in R, it should print useful information about your setup.

**Comment by 22459** [comment]
Ok I will do that. Wouldn't this be some kind of interaction problem with lyx/lualatex though?

**Comment by krlmlr** [comment]
That's what I'd like to find out.

**Comment by 22459** [comment]
Ok here's that log:

```
> library(tikzDevice)
> options(tikzDefaultEngine="luatex")
> tikzTest()

Active compiler:
	/nix/store/hkchzp15q9g74fy5vvjz375gnxkwbim0-texlive-combined-full-2017/bin/lualatex
	This is LuaTeX, Version 1.0.4 (Web2C 2017/NixOS.org)
	

Measuring dimensions of: A
Running command: '/nix/store/hkchzp15q9g74fy5vvjz375gnxkwbim0-texlive-combined-full-2017/bin/lualatex' -interaction=batchmode -halt-on-error -output-directory '/run/user/1000/Rtmpz6Oq2J/tikzDevice68003f02f711' '/run/user/1000/Rtmpz6Oq2J/tikzDevice68003f02f711/tikzStringWidthCalc.tex'
This is LuaTeX, Version 1.0.4 (Web2C 2017/NixOS.org) 
 restricted system commands enabled.

luaotfload | main : initialization completed in 0.119 seconds
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: "File not found: lmroman10-regular.".[1] 7.5
```

**Comment by krlmlr** [comment]
Thanks, `tikzTest()` doesn't see any problems. (The essential output is `[1] 7.5` at the end, and the fact that it has run successfully. We might want to add a newline.)

@yihui: Do you have experience with LyX + knitr?

**Comment by 22459** [comment]
I forgot to mention because I was tired, but it does work if I don't use the tikz device.
Also I tried a simple switch to xetex and it has the same issue, so I think it might not be a lualatex problem.

**Comment by 22459** [comment]
Is there anything helpful I can do to make progress with this?

**Comment by krlmlr** [comment]
I can try running your `.lyx` file. How do I do that?

**Comment by 22459** [comment]
You just open it in lyx and find the "render (pdflatex)" or "view" or something in one of the menus. Theres also a toolbar icon for it. It's the eyes. I'd be more specific but I'm in the middle of building it so I can't run it right now.

Does anything seem to be missing?

**Comment by krlmlr** [comment]
Thanks. Can I run it from the command line?

**Comment by 22459** [comment]
Hm. I don't know. 

Apparently yes: https://tex.stackexchange.com/questions/175345/how-to-use-lyx-to-create-pdf-file-from-the-command-line

The format for lualatex is pdf5.

**Comment by 22459** [comment]
@krlmlr have you had any luck with it?

**Comment by krlmlr** [comment]
When running `lyx --export pdf4 HU.lyx` on your document, I'm seeing:

```
This is LuaTeX, Version 1.0.4 (TeX Live 2017/Debian) 
 restricted system commands enabled.

! LaTeX Error: *** this package currently works only with XeTeX ***
 You are not using XeTeX, so we are exiting cleanly!
 Continuing may lead to 'unavailable font metrics' errors!
.
```

Changing to `options(tikzDefaultEngine = "xetex")` by editing your `.lyx` document in a text editor allowed me to compile it. Does that help?

**Comment by bellackn** [comment]
Closing this issue since it appears to be resolved. Please feel free, if this is still an issue, to leave a comment requesting this issue be reopened.
