### ISSUE TITLE
Package is orphaned on CRAN

### ISSUE THREAD

**Issue by QuLogic** [daqana/tikzDevice#177]
Even though 0.11 was just posted a few days ago, CRAN seems to think the package is orphaned. See the [PDF manual](https://cran.r-project.org/web/packages/tikzDevice/tikzDevice.pdf) or check the `DESCRIPTION` file [in CRAN's source tarball](https://cran.r-project.org/src/contrib/tikzDevice_0.11.tar.gz).

This GitHub repo doesn't seem to indicate that this package is orphaned.

**Comment by rstub** [comment]
Thanks for your concern. As new maintainer have just submitted version 0.12 to CRAN.
